export const GiftsForWomen = [
  {
    image: "https://au.louisvuitton.com/content/dam/lv/online/high-end/unisex/gift/U_Gift_Guide_Valentines_Day_2024.html/jcr:content/assets/BC_VALENTINESDAY2024_140_women_heart_DII.jpg?imwidth=730",
    name: "Keep My Heart",
    price: "3,150",
    featured: true,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-alma-bb--M53152_PM2_Front%20view.png?imwidth=1090",
    name: "Alma",
    price: "2,870",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-keep-my-heart--M82966_PM2_Front%20view.png?imwidth=1090",
    name: "Keep My Heart",
    price: "3,150",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louisa-bracelet--M1429A_PM2_Front%20view.png?imwidth=730",
    name: "Louisa Bracelet",
    price: "920",
    featured: true,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-iconic-ring--M1461X_PM2_Front%20view.png?imwidth=1090",
    name: "LV Iconic Ring",
    price: "630",
    featured: true,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-spell-on-you-lv-remix--LP0373_PM2_Front%20view.png?imwidth=730",
    name: "Alma",
    price: "2,870",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-keep-my-heart--M82966_PM2_Front%20view.png?imwidth=1090",
    name: "Keep My Heart",
    price: "3,150",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-charms-card-holder--M82739_PM2_Front%20view.png?imwidth=730",
    name: "Keep My Heart",
    price: "3,150",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-my-true-lv-square-70--M78061_PM2_Front%20view.png?imwidth=730",
    name: "My True LV Square 70",
    price: "600",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/content/dam/lv/online/high-end/unisex/gift/U_Gift_Guide_Valentines_Day_2024.html/jcr:content/assets/BC_VALENTINESDAY2024_170_women_sunglasses_cat_eye_DII.jpg?imwidth=730",
    name: "",
    price: "",
    featured: true,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-metis-east-west--M46914_PM2_Front%20view.png?imwidth=730",
    name: "Pochette Metis West",
    price: "4800",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-circle-cat-eye-sunglasses--Z2109W_PM2_Front%20view.png?imwidth=730",
    name: "LV Circle Cat Eye Sunglasses",
    price: "725",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/content/dam/lv/online/high-end/unisex/gift/U_Gift_Guide_Valentines_Day_2024.html/jcr:content/assets/BC_VALENTINESDAY2024_180_chocolate_box_DII.jpg?imwidth=730",
    name: "",
    price: "",
    featured: true,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-pink-gold-and-diamond--Q93281_PM2_Front%20view.png?imwidth=730",
    name: "",
    price: "",
    featured: true,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-go14-square-sunglasses--Z2427W_PM2_Front%20view.png?imwidth=730",
    name: "LV GO14 Square Sunglasses",
    price: "940",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-capucines-compact-wallet--M63740_PM2_Front%20view.png?imwidth=730",
    name: "Capucines Compact Wallet",
    price: "1,490",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mini-dauphine--M45959_PM2_Front%20view.png?imwidth=730",
    name: "Mini Dauphine",
    price: "5,350",
    featured: false,
  },
  {
    image: "https://au.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-bloom-bracelet--M8532Z_PM2_Front%20view.png?imwidth=730",
    name: "LV Bloom Bracelet",
    price: "615",
    featured: false,
  },
]